name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set commit output
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      shell: bash

    - name: Set artifact name output
      id: artifact
      shell: bash
      run: |
        echo "::set-output name=artifact_name::${{ env.ECR_URL }}:${{steps.vars.outputs.sha_short}}"
        echo "::set-output name=artifact_name_latest::${{ env.ECR_URL }}:latest"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        target: service
