version: '2.3'
services:
  api:
    restart: on-failure
    scale: 1
    mem_limit: 1024m
    command: ["pm2-runtime", "ecosystem.config.js", "--only", "api"]
    build:
      context: .
      target: service
      dockerfile: Dockerfile
    ports:
      - 9000:9000

  frontend:
    restart: on-failure
    scale: 1
    mem_limit: 1024m
    command: ["pm2-runtime", "ecosystem.config.js", "--only", "frontend"]
    build:
      context: .
      target: service
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  postgres:
    image: postgres:9.6.1-alpine
    env_file:
      - ./common.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:6.0-rc3-alpine
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

volumes:
  pgdata:
    driver: local
  elasticsearch:
    driver: local
